#!/bin/zsh

install_pythons() {
  echo "--- Install Python ---"
  PythonVersions=( '3.7.4' '2.7.16' );
  for version in "${PythonVersions[@]}"; do
    pyenv install $version
  done

  echo ${PythonVersions[0]} > ~/.python-version
}
