#!/bin/zsh

install_pythons() {
  echo "--- Install Python ---"
  PythonVersions=( '3.5.2' '2.7.12' );
  for version in "${PythonVersions[@]}"; do
    pyenv install $version
  done

  echo ${PythonVersions[0]} > ~/.python-version
}
