#!/bin/zsh

install_rubies() {
  echo "--- Install Rubies ---"
  RubyVersions=( '2.6.3' '2.5.5' );
  for version in "${RubyVersions[@]}"; do
    ruby-install ruby $version
  done

  echo "ruby-${RubyVersions[0]}" > "$HOME/.ruby-version"
}

install_gems() {
  echo "--- Install Gems ---"
  cp config/.gemrc $HOME
  cp config/.railsrc $HOME
  gem install bundler
  bundle install
}
