cask_args appdir: '/Applications'
tap "caskroom/cask"

brew "chruby"
brew "git"
brew "heroku-toolbelt"
brew "imagemagick"
brew "ruby-install"
brew "node"
brew "phantomjs"
brew "pyenv"
brew "the_silver_searcher"
brew "unrar"
brew "wget"

cask "atom"
cask "dash"
cask "dropbox"
cask "firefox"
cask "flux"
cask "gimp"
cask "github-desktop"
cask "gitx"
cask "google-chrome"
cask "iterm2"
cask "paintbrush"
cask "postgres"
cask "seashore"
cask "shiftit"
cask "slack"
cask "steam"
cask "sublime-text"
cask "transmission"
cask "vlc"
