#!/bin/bash
set -e
exec > >(tee $0.log) 2>&1

black="\033[0;30m"
dark_gray="\033[1;30m"
red="\033[0;31m"
light_red="\033[1;31m"
green="\033[0;32m"
light_green="\033[1;32m"
brown="\033[0;33m"
yellow="\033[1;33m"
blue="\033[0;34m"
light_blue="\033[1;34m"
purple="\033[0;35m"
light_purple="\033[1;35m"
cyan="\033[0;36m"
light_cyan="\033[1;36m"
light_gray="\033[0;37m"
white="\033[1;37m"
no_color="\033[0m"

success() {
  printf "${cyan}[SUCCESS]${no_color} $*"
}

warning() {
  printf "${light_purple}[WARNING]${no_color} $*"
}

response() {
  printf " ${yellow}Response:${no_color} ${white}$*${no_color}\n"
}

check_exit_code() {
  exit_code=$1
  positive_msg=$2
  negative_msg=$3

  if [ $exit_code -eq 0 ]; then
    success $positive_msg
  else
    success $negative_msg
  fi
}

check_zsh() {
  username=$(whoami)
  shell_name=$(finger $username | grep -o "Shell:.*")

  if [[ "$shell_name" == "Shell: /bin/zsh" ]]; then
    success "$username's shell is /bin/zsh!"
  else
    warning "$username's shell is not /bin/zsh!"
  fi

  response $shell_name
}

version() {
  cmd=$1
  flag=$2
  version=$(eval "$1 $2")
  check_exit_code $? "$cmd was detected!" "$cmd was not detected!"
  response $version
}

main() {
  version "xcode-select" "-v"
  check_zsh
  version "brew" "-v"
  version "git" "--version"
  version "atom" "-v"

  # check apps (atom git slack)
  # oh-my-zsh
  # chruby
  # which ruby
  # et
}

main
