#!/bin/bash
exec > >(tee "$0".log) 2>&1

cyan="\033[0;36m"
light_purple="\033[1;35m"
yellow="\033[1;33m"
white="\033[1;37m"
no_color="\033[0m"

success() {
  printf "${cyan}[SUCCESS]${no_color} $*"
}

warning() {
  printf "${light_purple}[WARNING]${no_color} $*"
}

response() {
  printf "\r\n  ${yellow}Response:${no_color} ${white}$*${no_color}\r\n"
}

check() {
  cmd=$1
  flag=$2

  if $(command -v $cmd >/dev/null); then
    result=$(eval "$cmd $flag")
    success "$cmd was detected"
    response "$result"
  else
    warning "$cmd was not detected!\r\n"
  fi
}

check_ruby() {
  ruby_path=$(which ruby)

  if [[ "$ruby_path" == "$HOME/.rubies"* ]]; then
    ruby_version=$(ruby -v)
    success "$ruby_version was detected in the home folder!"
  else
    warning "Not using a ruby version manager!"
  fi

  response "$ruby_path"
}

check_zsh() {
  username=$(whoami)
  shell_name=$(finger $username | grep -o "Shell:.*")

  if [[ "$shell_name" == *"/bin/zsh" ]]; then
    success "$username's shell is /bin/zsh!"
  else
    warning "$username's shell is not /bin/zsh!"
  fi

  response "$shell_name"
}

main() {
  check_zsh
  check "xcode-select" "-v"
  check "brew" "-v"
  check_ruby
  check "heroku" "version"
  check "git" "--version"
  check "psql" "--version"
  check "atom" "-v"
  check "et" "-v"
  check "rspec" "-v"
  check "rails" "-v"
}

main
